### ISSUE TITLE
<var>

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_hxx#11]
```html
<var {x=1, y=foo()}>
  ...
</var>
```

get translated to:

```html
<switch {[1, foo()]}>
  <case {[x, y]}>
    ...
</switch>
```

What do you think?

**Comment by back2dos** [comment]
Ah, sorry, yeah, we can do something like that. That said, [`<var>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var) actually seems to be a valid HTML tag.

So I guess our options are `using` or `let` or `with` or something.

On the other hand, I guess giving `{var x = 1, y = foo()}` special treatment (i.e. not adding it to the output) also might do the trick?

**Comment by kevinresol** [comment]
yeah, anything that works
