### ISSUE TITLE
A Tutorial on how to write a generator?

### ISSUE THREAD

**Issue by darmie** [haxetink/tink_hxx#17]
While pointing us to VDOM library as an example of generator. It's not still very clear to me how to go about writing a custom generator. 

Could you please provide a simple step-by-step guide on how to write a generator?

**Comment by back2dos** [comment]
Sorry, the doc is a bit outdated in that regard.

There is a [default generator](https://github.com/haxetink/tink_hxx/blob/master/src/tink/hxx/Generator.hx), that actually interprets tags in a way that makes them usable: https://github.com/haxetink/tink_hxx#default-semantics

Unless you have something super special in mind, I would suggest just using that ;)

**Comment by darmie** [comment]
Thank you!

**Comment by back2dos** [comment]
If you get stuck, ping me on gitter. I'm going to leave this open as a reminder to update the docs ;)

**Comment by darmie** [comment]
I am getting `Type not found: Generator`, what should I do?

**Comment by back2dos** [comment]
Closing in favor of https://github.com/MVCoconut/coconut.diffing/issues/1
