### ISSUE TITLE
react-next project won't compile

### ISSUE THREAD

**Issue by axelhuizinga** [haxetink/tink_hxx#25]
:\devel\crm-connect\.haxelib\tink_hxx/0,20,0/src/tink/hxx/Generator.hx:69: characters 62-174 : { pos : haxe.macro.Position, expr : haxe.macro.ExprDef } has no field as
c:\devel\crm-connect\.haxelib\tink_hxx/0,20,0/src/tink/hxx/Generator.hx:72: characters 81-91 : haxe.macro.Expr has no field as
c:\devel\crm-connect\.haxelib\tink_hxx/0,20,0/src/tink/hxx/Generator.hx:318: characters 76-104 : haxe.macro.ComplexType has no field getFieldSuggestions
c:\devel\crm-connect\.haxelib\tink_hxx/0,20,0/src/tink/hxx/Generator.hx:318: characters 76-104 : haxe.macro.ComplexType has no field getFieldSuggestions

**Comment by back2dos** [comment]
You'll have to update tink_macro to at least 0.17.2 ;)
