### ISSUE TITLE
Support keyValueIterator

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_hxx#30]
Currently this code will result in `invalid loop head`:
`<for ${key => value in iterable}>`

**Comment by kLabz** [comment]
Strange, I used them often with react-next

**Comment by kevinresol** [comment]
I just realized why hxx says so. Because I am using coconut and tink_lang gets into the way, converting `key => value` into `function(key) return value` which is what hxx sees. Shall we disable tink_lang's arrow lambda in haxe 4?
