### ISSUE TITLE
Support  rendering `${}` as plain text

### ISSUE THREAD

**Issue by markknol** [haxetink/tink_hxx#37]
For a code example I want to do this `Use <code>variant=${Large}</code> instead`

I tried  `<code>variant=\0024\007BLarge\007D</code>` but that renders `variant=4BLargeD`.

It would be nice if we could use `$${}` which skips the string interpolation entirely and renders `${}` as plain text.

**Comment by kLabz** [comment]
Workaround: 

```haxe
var code = "variant=${Large}";
// ...
<code>{code}</code>
```

**Comment by kLabz** [comment]
On another note, imo escaping `{` is a better solution than escaping `$` since `$` is optional in interpolation.

**Comment by back2dos** [comment]
> On another note, imo escaping `{` is a better solution than escaping `$` since `$` is optional in interpolation.

I don't mind supporting that, but `$${expr}` and `$$ident` are supported on lexer level as a means to avoid interpolation and the parser should definitely be made able to handle it.

**Comment by kLabz** [comment]
Makes sense.
`$${Large}` would render as `${Large}`, right? How would you render `{Large}`?

**Comment by markknol** [comment]
> $${Large} would render as ${Large}, right? How would you render {Large}?

I think the idea is that you can do $${'whatever'}`, so then you can do `$${'${'}Large$${'}'}` ?

**Comment by kLabz** [comment]
Just do `{"${Large}"}` right now if you want to do something like that :P

**Comment by markknol** [comment]
> Just do {"${Large}"} right now if you want to do something like that :P

Oh does that work? 
Looks like its fixed now :o nice :)
