### ISSUE TITLE
Comments break interpolation

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_hxx#39]
```haxe
class App extends coconut.vdom.View {
    
    function render() '
        <if ${true /* breakme */}>
            <div>${' ${foo()} '}</div>
        </if>
    ';
    
    function foo() return 'bar';
}
```

this will render `${foo()}` instead of `bar`
removing the comment fixes it

**Comment by back2dos** [comment]
That's a problem in Haxe's lexer: https://github.com/HaxeFoundation/haxe/issues/9370

Available workarounds for the time being: `<if {true /* breakmenot */}` or `<if ${true}><!-- breakmenot -->` or Haxe 4 inline markup.
