### ISSUE TITLE
Cannot extract with `=>`

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_hxx#4]
A switch case like this:
```
<case ${_.split('/') => ['', 'products', id]}>
```

Fails with:
```
Unknown identifier : _
For optional function argument 'children'
```

I think `=>` is treated as short lambda.

**Comment by back2dos** [comment]
Hmm, my guess is it's actually interpreted as [a trailing argument](https://haxetink.github.io/tink_lang/#/implementation-sugar/trailing-arguments). If that's the case then `<case ${(_.split('/')) => ['', 'products', id]}>` should work around it ;)

**Comment by kevinresol** [comment]
Looks like so
