### ISSUE TITLE
feature request: interpret hxx at runtime

### ISSUE THREAD

**Issue by markknol** [haxetink/tink_hxx#40]
> **me**: maybe going to far now, but would we be able to execute coconut at runtime? was thinking if it would be possible to have a realtime examples in a playground/editor? `editorOutput.innerHTML = coconut.html.Renderer.render(editorTextArea.value);`
>
> **you**: back2dos well, that's going to be pretty hard. probably less work to compile Haxe via js_of_ocaml / bucklescript / reason and run it in the browser
>
> **me**: I thought maybe if it was already known in the build which components there were available, you woudnt need the whole compiler maybe
>
> **you**: although ... hmm ... now that hscript has a typer, it might be possible to interpret hxx at runtime

💡

**Comment by back2dos** [comment]
While this might be nice, it'd be a massive undertaking. I prefer to focus effort on some semblance of IDE support.
