### ISSUE TITLE
Runtime error when using width or height attributes on svg elements

### ISSUE THREAD

**Issue by cambiata** [haxetink/tink_hxx#43]
Setting the `width` or `height` attributes on a svg element casuses a runtime error (in Windows Chrome and Firefox at least):
`Uncaught TypeError: Cannot assign to read only property 'height' of object '#<SVGSVGElement>`
`    at coconut_vdom__$Html_Svg.setSvgProp (client.js:4618)`
`    at coconut_vdom__$Html_Svg.create (client.js:4675)`
`    at coconut_diffing_Differ.createNative (client.js:3856)`
`    at Object.native (client.js:3652)`
etc.

**Comment by cambiata** [comment]
The same goes for polygon `points` attribute:
```<polygon points="16.172 . . ."/>```
Causes the same kind of runtime error.

**Comment by kevinresol** [comment]
I assume you are using coconut, if so, please specific which backend you are using.

**Comment by cambiata** [comment]
Yes, the error occurs at runtime when rendering through `coconut.vdom`.

For example, adding a `width` attribute to the svg in [this example](https://github.com/MVCoconut/coconut.html/blob/master/tests/Playground.hx) and rendering through `coconut.vdom` causes the error.

**Comment by cambiata** [comment]
Closed this one - Created a pull request in coconut.vdom with simple solution.
