### ISSUE TITLE
hxx shorthand (string literal as function body) is not working for @:attr function

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_hxx#50]
The following will error with `String should be Int` pointing at the `$e`

```haxe
class Foo extends View {
	@:attr function renderChildren(outcome:Outcome<Int, String>) '
		<switch ${outcome}>
			<case ${Success(v)}>$v
			<case ${Failure(e)}>$e
		</switch>
	';
	
	function render() return renderChildren(Success(1));
}
```

changing to `@:attr function renderChildren(outcome:Outcome<Int, String>):RenderResult return coconut.Ui.hxx('...');` will work

I reckon the compiler thinks renderChildren is a `Outcome->Void` function therefore triggering the "switch branch unification in void-returning function" issue. But merely tagging the return type doesn't help. I need to explicitly call the hxx function to make it work.

**Comment by back2dos** [comment]
This a coconut problem.
