### ISSUE TITLE
Give proper position in case of imported hxx errors

### ISSUE THREAD

**Issue by grosmar** [haxetink/tink_hxx#8]
When using `{import "MyView.html"}` the error positions always refererence for the first line with a large character number. I guess because it doesn't parse the newlines of the string. 
If it would, it would be much more convinient to find the source of bug

**Comment by back2dos** [comment]
This is a compiler issue. In macros, positions are defined by [min - max](https://api.haxe.org/haxe/macro/Position.html) ranges and the compiler actually converts that to lines/columns during output. It often (but not always) fails for non-haxe files.
